// Sample data — Directorio de titulados Construcción Civil / Ingeniería en Construcción UACh
// Foco: Los Ríos y Los Lagos. Datos ficticios pero plausibles.

window.APP_DATA = {
  miembros: [
    { iniciales: "RC", nombre: "Rodrigo Cárcamo", anio: 2014, region: "Los Ríos" },
    { iniciales: "MJ", nombre: "María José Soto", anio: 2017, region: "Los Lagos" },
    { iniciales: "FA", nombre: "Felipe Aguilar", anio: 2012, region: "Los Ríos" },
    { iniciales: "CC", nombre: "Camila Cárdenas", anio: 2019, region: "Los Lagos" },
    { iniciales: "JM", nombre: "Javier Muñoz", anio: 2010, region: "Los Ríos" },
    { iniciales: "PB", nombre: "Pablo Barrientos", anio: 2016, region: "Los Lagos" },
    { iniciales: "DV", nombre: "Daniela Villarroel", anio: 2020, region: "Los Ríos" },
    { iniciales: "AO", nombre: "Andrés Oyarzún", anio: 2013, region: "Los Lagos" },
  ],

  contactos: [
    {
      id: "c-001",
      tipo: "Subcontrato",
      rubro: "Movimiento de tierras",
      nombre: "Excavaciones Calle-Calle Ltda.",
      contacto: "Don Hernán Maldonado",
      fono: "+56 9 8421 7733",
      whatsapp: "+56984217733",
      email: "h.maldonado@calle-calle.cl",
      region: "Los Ríos",
      ciudad: "Valdivia",
      recomendadoPor: "Rodrigo Cárcamo",
      anioRecomendacion: 2024,
      rating: 4.7,
      reviews: 6,
      ultimoProyecto: "Edificio Pedro Aguirre Cerda, Valdivia",
      notas: "Equipo propio: 2 retroexcavadoras, 1 bulldozer D6. Cumple plazos. Factura al día 30.",
    },
    {
      id: "c-002",
      tipo: "Subcontrato",
      rubro: "Hormigón armado",
      nombre: "Hormigones del Sur SpA",
      contacto: "Ing. Patricio Vidal",
      fono: "+56 9 7612 4485",
      whatsapp: "+56976124485",
      email: "pvidal@hsur.cl",
      region: "Los Lagos",
      ciudad: "Puerto Montt",
      recomendadoPor: "Pablo Barrientos",
      anioRecomendacion: 2023,
      rating: 4.4,
      reviews: 9,
      ultimoProyecto: "Galpón industrial Alerce",
      notas: "Buen control de cubicación. Pedir certificados de probetas con 24 hrs.",
    },
    {
      id: "c-003",
      tipo: "Mano de obra",
      rubro: "Maestro enfierrador",
      nombre: "Jorge Catalán",
      contacto: "Jorge Catalán (directo)",
      fono: "+56 9 5544 1290",
      whatsapp: "+56955441290",
      email: "",
      region: "Los Ríos",
      ciudad: "Valdivia",
      recomendadoPor: "Felipe Aguilar",
      anioRecomendacion: 2025,
      rating: 5.0,
      reviews: 4,
      ultimoProyecto: "Vivienda Niebla, losa colaborante",
      notas: "Trabaja con cuadrilla de 3. Lee planos sin problema. Cobra por kg colocado.",
    },
    {
      id: "c-004",
      tipo: "Subcontrato",
      rubro: "Instalaciones sanitarias",
      nombre: "Sanitarias Reumén",
      contacto: "Sra. Ingrid Pérez",
      fono: "+56 9 6128 0044",
      whatsapp: "+56961280044",
      email: "contacto@reumen.cl",
      region: "Los Ríos",
      ciudad: "Paillaco",
      recomendadoPor: "María José Soto",
      anioRecomendacion: 2024,
      rating: 4.1,
      reviews: 5,
      ultimoProyecto: "Conjunto 12 viviendas DS49, Paillaco",
      notas: "Tramita recepción ESSAL sin demora. Subir SLEP a obra es lento si no se avisa.",
    },
    {
      id: "c-005",
      tipo: "Mano de obra",
      rubro: "Cuadrilla de carpintería",
      nombre: "Cuadrilla de Don Lucho",
      contacto: "Luis Aedo",
      fono: "+56 9 8870 6612",
      whatsapp: "+56988706612",
      email: "",
      region: "Los Lagos",
      ciudad: "Osorno",
      recomendadoPor: "Andrés Oyarzún",
      anioRecomendacion: 2025,
      rating: 4.8,
      reviews: 7,
      ultimoProyecto: "Estructura tabiquería Hotel Río Bueno",
      notas: "Trae 4 maestros + 2 jornales. Pide adelanto del 30%. Trabajo prolijo en encuentros.",
    },
    {
      id: "c-006",
      tipo: "Subcontrato",
      rubro: "Instalaciones eléctricas",
      nombre: "ElectroAustral Ingeniería",
      contacto: "Ing. Cristián Hueitra (TE-1)",
      fono: "+56 9 7305 9921",
      whatsapp: "+56973059921",
      email: "chueitra@electroaustral.cl",
      region: "Los Ríos",
      ciudad: "Valdivia",
      recomendadoPor: "Daniela Villarroel",
      anioRecomendacion: 2025,
      rating: 4.6,
      reviews: 8,
      ultimoProyecto: "Remodelación oficinas Edificio Prochelle",
      notas: "TE-1 vigente. Entrega TE-1 firmado a las 48h de recepción SEC.",
    },
    {
      id: "c-007",
      tipo: "Mano de obra",
      rubro: "Maestro de terminaciones",
      nombre: "Manuel Cheuquemán",
      contacto: "Manuel Cheuquemán",
      fono: "+56 9 6677 1183",
      whatsapp: "+56966771183",
      email: "",
      region: "Los Lagos",
      ciudad: "Puerto Varas",
      recomendadoPor: "Camila Cárdenas",
      anioRecomendacion: 2024,
      rating: 4.9,
      reviews: 5,
      ultimoProyecto: "Casa lago Llanquihue, terminaciones interiores",
      notas: "Excelente en porcelanato y cornisas. Pide herramienta propia + alojamiento.",
    },
    {
      id: "c-008",
      tipo: "Subcontrato",
      rubro: "Movimiento de tierras",
      nombre: "Áridos y Excavaciones Ranco",
      contacto: "Don Patricio Ñancul",
      fono: "+56 9 5128 4407",
      whatsapp: "+56951284407",
      email: "aridosranco@gmail.com",
      region: "Los Ríos",
      ciudad: "La Unión",
      recomendadoPor: "Javier Muñoz",
      anioRecomendacion: 2023,
      rating: 3.9,
      reviews: 4,
      ultimoProyecto: "Camino interior fundo Quilacahuín",
      notas: "Conviene para volúmenes grandes. Maquinaria con años — confirmar disponibilidad.",
    },
    {
      id: "c-009",
      tipo: "Mano de obra",
      rubro: "Soldador calificado",
      nombre: "Víctor Painemil",
      contacto: "Víctor Painemil",
      fono: "+56 9 4422 9981",
      whatsapp: "+56944229981",
      email: "",
      region: "Los Ríos",
      ciudad: "Valdivia",
      recomendadoPor: "Rodrigo Cárcamo",
      anioRecomendacion: 2025,
      rating: 4.7,
      reviews: 3,
      ultimoProyecto: "Estructura metálica techo bodega ZEAL",
      notas: "Soldadura GMAW y SMAW. Calificación 6G. Pide consumibles incluidos.",
    },
    {
      id: "c-010",
      tipo: "Subcontrato",
      rubro: "Pinturas y revestimientos",
      nombre: "Pinturas Chiloé",
      contacto: "Sergio Bahamonde",
      fono: "+56 9 8855 4471",
      whatsapp: "+56988554471",
      email: "pinturaschiloe@outlook.cl",
      region: "Los Lagos",
      ciudad: "Castro",
      recomendadoPor: "Pablo Barrientos",
      anioRecomendacion: 2024,
      rating: 4.3,
      reviews: 6,
      ultimoProyecto: "Edificio costanera Castro, fachada exterior",
      notas: "Trabaja con Sherwin Williams y Ceresita. Andamios propios. Llueve mucho — coordinar.",
    },
    {
      id: "c-011",
      tipo: "Mano de obra",
      rubro: "Maestro instalador gasfíter",
      nombre: "Don Eleodoro Ojeda",
      contacto: "Eleodoro Ojeda (SEC clase 3)",
      fono: "+56 9 7790 3325",
      whatsapp: "+56977903325",
      email: "",
      region: "Los Lagos",
      ciudad: "Puerto Montt",
      recomendadoPor: "Andrés Oyarzún",
      anioRecomendacion: 2024,
      rating: 4.5,
      reviews: 4,
      ultimoProyecto: "Sala de calderas Hotel Frutillar",
      notas: "Sello SEC al día. Atiende emergencias post-entrega. Cobra UF por punto.",
    },
    {
      id: "c-012",
      tipo: "Subcontrato",
      rubro: "Estructura metálica",
      nombre: "Maestranza Calle-Calle",
      contacto: "Ing. Roberto Sandoval",
      fono: "+56 9 6234 1108",
      whatsapp: "+56962341108",
      email: "rsandoval@maestranzacc.cl",
      region: "Los Ríos",
      ciudad: "Valdivia",
      recomendadoPor: "Felipe Aguilar",
      anioRecomendacion: 2025,
      rating: 4.8,
      reviews: 11,
      ultimoProyecto: "Galpón frigorífico, San José de la Mariquina",
      notas: "Muy buenos para diseño-construcción. Entregan planos taller. Pintura epóxica adicional.",
    },
  ],

  solicitudes: [
    {
      id: "s-001",
      autor: "Daniela Villarroel",
      iniciales: "DV",
      tiempo: "hace 2 horas",
      texto: "Alguien tiene contacto de cuadrilla de hormigón en Río Bueno? Necesito vaciar radier 180 m² la próxima semana y mi maestro habitual cae con licencia.",
      respuestas: 3,
      etiqueta: "Mano de obra",
      region: "Los Ríos",
      estado: "abierta",
    },
    {
      id: "s-002",
      autor: "Pablo Barrientos",
      iniciales: "PB",
      tiempo: "hace 5 horas",
      texto: "Estoy cotizando aislante poliuretano proyectado para galpón en Puerto Montt (1.200 m²). Algún proveedor confiable que haya trabajado alguno de ustedes? Mejor si tiene certificación de densidad.",
      respuestas: 5,
      etiqueta: "Subcontrato",
      region: "Los Lagos",
      estado: "abierta",
    },
    {
      id: "s-003",
      autor: "Rodrigo Cárcamo",
      iniciales: "RC",
      tiempo: "ayer",
      texto: "Necesito topógrafo con dron para levantamiento de 8 hás en La Unión. Plazo apretado, parto la próxima semana.",
      respuestas: 7,
      etiqueta: "Servicio",
      region: "Los Ríos",
      estado: "resuelta",
    },
    {
      id: "s-004",
      autor: "Camila Cárdenas",
      iniciales: "CC",
      tiempo: "ayer",
      texto: "Recomendaciones de subcontrato de revestimiento en alerce / lenga para casa en orilla de lago. Cliente exige procedencia legal de la madera.",
      respuestas: 2,
      etiqueta: "Subcontrato",
      region: "Los Lagos",
      estado: "abierta",
    },
    {
      id: "s-005",
      autor: "Javier Muñoz",
      iniciales: "JM",
      tiempo: "hace 3 días",
      texto: "Atención: Don Lucho (cuadrilla carpintería Osorno) está con disponibilidad enero–marzo. Lo dejo acá por si a alguien le sirve, lo recomiendo.",
      respuestas: 4,
      etiqueta: "Aviso",
      region: "Los Lagos",
      estado: "informativa",
    },
    {
      id: "s-006",
      autor: "Felipe Aguilar",
      iniciales: "FA",
      tiempo: "hace 4 días",
      texto: "Alguien sabe si Sanitarias Reumén sigue trabajando con DS49? Tengo proyecto adjudicado y necesito confirmar.",
      respuestas: 3,
      etiqueta: "Subcontrato",
      region: "Los Ríos",
      estado: "resuelta",
    },
  ],

  // ---- Detalle por contacto: hoja de vida técnica ----
  // Llave = contacto id. Si no existe, se muestra una vista mínima.
  detalles: {
    "c-001": {
      historial: [
        { obra: "Edificio Pedro Aguirre Cerda, Valdivia", faena: "Excavación masiva 1.800 m³", anio: 2024, conQuien: "Rodrigo Cárcamo" },
        { obra: "Conjunto 18 viviendas DS49, Paillaco", faena: "Movimiento de tierras y rellenos", anio: 2023, conQuien: "Felipe Aguilar" },
        { obra: "Galpón industrial Las Ánimas", faena: "Excavación zapatas + relleno compactado", anio: 2022, conQuien: "Rodrigo Cárcamo" },
      ],
      comentarios: [
        { autor: "Rodrigo Cárcamo", iniciales: "RC", texto: "Equipo propio: 2 retroexcavadoras y 1 bulldozer D6. Don Hernán llega a la obra a las 7:30 sin falla. Cumple plazos y factura al día 30 sin tirar la cuerda.", fecha: "Mar 2024" },
        { autor: "Felipe Aguilar", iniciales: "FA", texto: "Lo recomiendo, eso sí avisar con anticipación. En verano andan ocupados con caminos forestales.", fecha: "Oct 2023" },
      ],
      fortalezas: ["Equipo propio", "Cumple plazos", "Lectura de planos", "Factura al día 30"],
      fotos: [
        { color: "#3a4a5e", label: "Excavación zapatas\nAv. PAC, Valdivia" },
        { color: "#5a6b7e", label: "Compactado\nbase radier" },
      ],
    },
    "c-003": {
      historial: [
        { obra: "Vivienda Niebla, losa colaborante", faena: "Enfierradura losa 95 m²", anio: 2025, conQuien: "Felipe Aguilar" },
        { obra: "Edificio Plaza Osorno", faena: "Enfierradura losas pisos 3 a 5", anio: 2024, conQuien: "Pablo Barrientos" },
        { obra: "Bodega frigorífica Lanco", faena: "Enfierradura fundaciones + pilares", anio: 2024, conQuien: "Rodrigo Cárcamo" },
        { obra: "Casa Niebla 2da etapa", faena: "Refuerzo losa entrepiso", anio: 2023, conQuien: "Felipe Aguilar" },
      ],
      comentarios: [
        { autor: "Felipe Aguilar", iniciales: "FA", texto: "La cuadrilla es de 3 personas, son rápidos pero hay que asegurarles el suministro de fierro temprano porque rinden mucho. Lee planos sin problema y respeta detalles de armadura.", fecha: "Abr 2025" },
        { autor: "Pablo Barrientos", iniciales: "PB", texto: "Cobra por kg colocado, ojo con cubicar bien. Llega con sus propios alicates y trabaja con casco y arnés sin que se le pida.", fecha: "Ago 2024" },
        { autor: "Rodrigo Cárcamo", iniciales: "RC", texto: "Excelente para trabajos de poco metraje pero con detalle. Para volúmenes grandes mejor coordinar con anticipación.", fecha: "Jun 2024" },
      ],
      fortalezas: ["Lectura de planos", "Autocuidado / EPP", "Herramienta propia", "Cuadrilla estable", "Trabaja a trato"],
      fotos: [
        { color: "#4d3d2a", label: "Armadura losa\nNiebla 2025" },
        { color: "#6b5a3d", label: "Detalle anclaje\npilar-losa" },
        { color: "#857455", label: "Faena limpia\npost vaciado" },
      ],
    },
    "c-006": {
      historial: [
        { obra: "Remodelación oficinas Edificio Prochelle", faena: "Tablero general + canalizaciones", anio: 2025, conQuien: "Daniela Villarroel" },
        { obra: "Vivienda particular Isla Teja", faena: "Inst. eléctrica completa + TE-1", anio: 2024, conQuien: "Daniela Villarroel" },
        { obra: "Local comercial Calle Independencia", faena: "Modificación tablero + iluminación", anio: 2023, conQuien: "María José Soto" },
      ],
      comentarios: [
        { autor: "Daniela Villarroel", iniciales: "DV", texto: "Cristián entrega el TE-1 firmado a las 48 horas de la recepción SEC, sin atrasos. Trabaja con materiales de marca (Legrand, Schneider) y pasa boletas detalladas.", fecha: "Mar 2025" },
        { autor: "María José Soto", iniciales: "MJ", texto: "Buen trato con cliente final. Si el cliente le pregunta algo técnico explica con paciencia. Eso vale.", fecha: "Sep 2023" },
      ],
      fortalezas: ["TE-1 vigente", "Documentación impecable", "Marcas reconocidas", "Trato con cliente"],
      fotos: [
        { color: "#2a3d4d", label: "Tablero general\nProchelle" },
        { color: "#4a5d6d", label: "Canalización\noficinas piso 4" },
      ],
    },
    "c-008": {
      historial: [
        { obra: "Camino interior fundo Quilacahuín", faena: "Movimiento de tierras 4.200 m³", anio: 2026, conQuien: "Javier Muñoz" },
        { obra: "Conjunto habitacional La Unión", faena: "Excavación zanjas + relleno", anio: 2023, conQuien: "Javier Muñoz" },
      ],
      comentarios: [
        { autor: "Javier Muñoz", iniciales: "JM", texto: "Sirven para volúmenes grandes y precios competitivos, pero la maquinaria tiene años. En Quilacahuín se me cortó la faena dos días por falla hidráulica de la retro y no tenían reemplazo. Para obras chicas con plazos apretados, no.", fecha: "Mar 2026" },
      ],
      fortalezas: ["Precios competitivos", "Volúmenes grandes"],
      fotos: [
        { color: "#5a4a3d", label: "Apertura camino\nQuilacahuín" },
      ],
    },
    "c-012": {
      historial: [
        { obra: "Galpón frigorífico, San José de la Mariquina", faena: "Estructura metálica 680 m²", anio: 2025, conQuien: "Felipe Aguilar" },
        { obra: "Pasarela peatonal Río Cruces", faena: "Estructura + montaje", anio: 2024, conQuien: "Rodrigo Cárcamo" },
        { obra: "Bodega industrial Collico", faena: "Cerchas + costaneras", anio: 2024, conQuien: "Felipe Aguilar" },
        { obra: "Ampliación maestranza propia", faena: "Pórticos + revestimiento", anio: 2023, conQuien: "Pablo Barrientos" },
      ],
      comentarios: [
        { autor: "Felipe Aguilar", iniciales: "FA", texto: "Muy buenos para diseño-construcción. Roberto entrega planos de taller revisados antes del montaje y se hace cargo si hay un error de fabricación. Pintura epóxica se cobra aparte.", fecha: "Ene 2025" },
        { autor: "Rodrigo Cárcamo", iniciales: "RC", texto: "En la pasarela del Río Cruces el montaje se hizo en una sola jornada. Cuadrilla de 6 con grúa subcontratada. Plazos clavados.", fecha: "Sep 2024" },
        { autor: "Pablo Barrientos", iniciales: "PB", texto: "Trabajo prolijo en uniones, cordones de soldadura limpios. Pedirles certificados de calificación del soldador, los tienen.", fecha: "Mar 2023" },
      ],
      fortalezas: ["Diseño-construcción", "Planos de taller", "Calificación 6G", "Cumple plazos", "Cuadrilla propia"],
      fotos: [
        { color: "#3d3a36", label: "Pórticos en taller\nMariquina" },
        { color: "#4d4a44", label: "Montaje\nGalpón frigorífico" },
        { color: "#5d5a52", label: "Cordón soldadura\ndetalle" },
        { color: "#6d6a60", label: "Pintura epóxica\nestructura final" },
      ],
    },
  },

  alertas: [
    {
      id: "a-001",
      contactoId: "c-008",
      proveedor: "Áridos y Excavaciones Ranco",
      rubro: "Movimiento de tierras",
      region: "Los Ríos",
      ciudad: "La Unión",
      severidad: "media",
      motivo: "Maquinaria antigua falló dos veces en obra",
      detalle: "Retroexcavadora se detuvo dos días seguidos por falla hidráulica. Tuve que arrendar reemplazo a último minuto y absorber el costo. No tenía equipo de respaldo disponible.",
      obra: "Camino interior fundo Quilacahuín",
      reportadoPor: "Javier Muñoz",
      iniciales: "JM",
      fecha: "Mar 2026",
    },
    {
      id: "a-002",
      contactoId: null,
      proveedor: "Constructora del Lago Ltda.",
      rubro: "Subcontrato fachada",
      region: "Los Lagos",
      ciudad: "Frutillar",
      severidad: "alta",
      motivo: "Abandonó obra con avance al 60% sin aviso",
      detalle: "Tomó anticipo del 40% y dejó de aparecer al mes y medio. Quedaron andamios montados y materiales en bodega. Difícil de ubicar después. Evitar.",
      obra: "Edificio costanera Frutillar",
      reportadoPor: "Camila Cárdenas",
      iniciales: "CC",
      fecha: "Feb 2026",
    },
    {
      id: "a-003",
      contactoId: null,
      proveedor: "Pinturas Llanquihue Express",
      rubro: "Pinturas",
      region: "Los Lagos",
      ciudad: "Puerto Varas",
      severidad: "alta",
      motivo: "Material vencido, mala adherencia",
      detalle: "Aplicaron látex con fecha vencida en muros interiores. A las tres semanas empezó a desprenderse. No quisieron rehacer sin recargo. No es Pinturas Chiloé (esos son buenos).",
      obra: "Casa lago Llanquihue",
      reportadoPor: "Camila Cárdenas",
      iniciales: "CC",
      fecha: "Ene 2026",
    },
    {
      id: "a-004",
      contactoId: null,
      proveedor: "Maestro 'Chino' (sin apellido confirmado)",
      rubro: "Mano de obra · estuco",
      region: "Los Ríos",
      ciudad: "Valdivia",
      severidad: "baja",
      motivo: "No respeta plazos comprometidos",
      detalle: "Se compromete con 4 ó 5 obras al mismo tiempo y desaparece días enteros. Trabajo cuando aparece es decente, pero no se puede planificar con él.",
      obra: "Vivienda Niebla",
      reportadoPor: "Felipe Aguilar",
      iniciales: "FA",
      fecha: "Abr 2026",
    },
  ],

  historial: [
    { fecha: "06 May 2026", quien: "Daniela Villarroel", accion: "abrió solicitud", detalle: "Cuadrilla hormigón en Río Bueno" },
    { fecha: "06 May 2026", quien: "Rodrigo Cárcamo", accion: "agregó contacto", detalle: "Víctor Painemil — Soldador calificado" },
    { fecha: "05 May 2026", quien: "Pablo Barrientos", accion: "calificó", detalle: "Hormigones del Sur SpA · 4.4 ★" },
    { fecha: "04 May 2026", quien: "Camila Cárdenas", accion: "agregó contacto", detalle: "Manuel Cheuquemán — Terminaciones" },
    { fecha: "03 May 2026", quien: "Javier Muñoz", accion: "comentó", detalle: "Áridos y Excavaciones Ranco — 'maquinaria con años'" },
    { fecha: "02 May 2026", quien: "Andrés Oyarzún", accion: "agregó contacto", detalle: "Don Eleodoro Ojeda — Gasfíter" },
    { fecha: "01 May 2026", quien: "Felipe Aguilar", accion: "cerró solicitud", detalle: "Sanitarias Reumén DS49 — confirmado" },
    { fecha: "29 Abr 2026", quien: "María José Soto", accion: "agregó contacto", detalle: "Sanitarias Reumén" },
    { fecha: "28 Abr 2026", quien: "Daniela Villarroel", accion: "calificó", detalle: "ElectroAustral Ingeniería · 4.6 ★" },
    { fecha: "26 Abr 2026", quien: "Rodrigo Cárcamo", accion: "agregó contacto", detalle: "Excavaciones Calle-Calle Ltda." },
  ],
};
